version: "3.9"

services:
  backend:
    build: ./backend
    container_name: simple_backend
    ports:
      - "5000:5000"
    restart: unless-stopped
    command: python app.py --host=0.0.0.0 --port=5000

  frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    container_name: simple_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    depends_on:
      - backend
    restart: unless-stopped
