services:
  backend:
    build: ./backend
    container_name: simple_backend
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: simple_frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
